### PR TITLE
[#324] Change ICTRP URL to get non-JS version of pages

### LINKED ISSUE #324: ICTRP collector broken?
Hi! As promised, I'll try to explain my issues with the ICTRP collector below, encountered while trying to work on #280. This is a blocker so far.

Snippet from Scrapy's log:

```
DEBUG:collectors.ictrp.parser:No main_id: ICTRP - http://apps.who.int/trialsearch/Trial3.aspx?trialid=NCT01267175
2016-08-24 07:28:53 [collectors.ictrp.parser] DEBUG: No main_id: ICTRP - http://apps.who.int/trialsearch/Trial3.aspx?trialid=NCT01267175
```

So we see the record being scraped is **NCT01267175**. The problem is I had no extracted values, so I went looking with `curl` at the page itself, and found that the page contains a JS redirector that kicks in about 1-2 seconds after loading the page with a JS capable browser. [Here's the source for the mentioned page](http://paste.debian.net/791226/).

I don't really know how the registry was before, but I suspect some changes on their website that intentionally break scraping in many cases.

So far, this is a blocker for at least #280, which had a vast number of occurrences originating in ICTRP collection and is now unreproducible.

Or (hopefully) I am doing something wrong and everything actually works. In which case the collectors docs would need to be updated.

### PR DESCRIPTION
**Pull request by victor-nitu**
As title says, I just did a simple `replace` to get **Trial2** instead of **Trial3** (kudos @roll for the hint)

upd.
added fixes https://github.com/opentrials/opentrials/issues/324 to merge issue and PR on waffle

### CODE REVIEW

**Comment by roll** [comment]
:+1:

**Comment by victor-nitu** [comment]
What's wrong with this Travis guy? Is it always failing or it's a new issue?
@roll, any ideas?

**Comment by roll** [comment]
@nightsh 
On PRs travis can't read secret env vars like `WAREHOUSE_URL` but we still use it somewhere in the code instead of the `TEST_WAREHOUSE_URL`.

**Comment by victor-nitu** [comment]
Thanks, makes sense :)

**Pull request merged**
