### PR TITLE
[#362] Only push containers when deploying

### PR DESCRIPTION
**Pull request by vitorbaptista**
Fixes opentrials/opentrials#362

### CODE REVIEW

**Comment by vitorbaptista** [comment]
This is failing because of a test that hits external servers. I modified this test on https://github.com/opentrials/collectors/pull/40, so we should be fine to merge this.

**Comment by roll** [comment]
@vitorbaptista 
do we need `make build` in tests at all? It slows down our travis testing.

**Comment by vitorbaptista** [comment]
@roll It's not that useful, but I like the extra safety net in case we mess with some of our Docker yaml files. Our build is quite fast as well, so it's fine IMO.

**Comment by victor-nitu** [comment]
I'd say... let's merge it? 👍

**Pull request merged**
